config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/fair-workflows/fairworkflows:
      branch: main
      repo: https://github.com/fair-workflows/fairworkflows
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/fair-workflows/fairworkflows git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cobalt-weasel.sh
        container: qc.acc_craggy-pumpkin-squirrel
  QC.Doc:
    repos:
      github.com/fair-workflows/fairworkflows find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-turquoise-mau.sh
        container: qc.doc_gimpy-vermilion-ocelot
      github.com/fair-workflows/fairworkflows git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-ultramarine-okapi.sh
        container: qc.doc_ready-amaranth-monster
      github.com/fair-workflows/fairworkflows markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-gold-cichlid.sh
        container: qc.doc_geeky-burgundy-hyrax
      github.com/fair-workflows/fairworkflows restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-emerald-boar.sh
        container: qc.doc_surly-celadon-sparrow
  QC.Lic:
    repos:
      github.com/fair-workflows/fairworkflows licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-white-dhole.sh
        container: qc.lic_shaky-buff-capybara
  QC.Met:
    repos:
      github.com/fair-workflows/fairworkflows cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-celadon-gopher.sh
        container: qc.met_stealthy-sapphire-iguana
  QC.Sec:
    repos:
      github.com/fair-workflows/fairworkflows bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cinnamon-hyrax.sh
        container: qc.sec_crabby-persimmon-drever
  QC.Sty:
    repos:
      github.com/fair-workflows/fairworkflows flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-taupe-falcon.sh
        container: qc.sty_seedy-myrtle-stingray
  QC.Ver:
    repos:
      github.com/fair-workflows/fairworkflows get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-tangerine-gopher.sh
        container: qc.ver_leaky-indigo-koala
timeout: 5400
